# This docker-compose will create a container containing a PostgreSQL and a Redis.
# Do not change this file unless you really know what you are doing.
# docker-compose up -d
version: '3.7'
services:
  postgres:
    image: postgres:14.0
    container_name: postgres-cadastro-usuario-teste2
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init2.sql
    ports:
      - '5432:5432'